// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

//Player
export const PAGINATION = 'PAGINATION';
export const FILTER = 'FILTER';
export const REQUEST_PLAYERS = 'REQUEST_PLAYERS';
export const RECEIVE_PLAYERS = 'RECEIVE_PLAYERS';

export const REQUEST_DELETE_PLAYER = 'REQUEST_DELETE_PLAYER';
export const SUCCESS_DELETE_PLAYER = 'SUCCESS_DELETE_PLAYER';
export const ERROR_DELETE_PLAYER = 'ERROR_DELETE_PLAYER';

export const REQUEST_CREATE_PLAYER = 'REQUEST_CREATE_PLAYER';
export const SUCCESS_CREATE_PLAYER = 'SUCCESS_CREATE_PLAYER';
export const ERROR_CREATE_PLAYER = 'ERROR_CREATE_PLAYER';